apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerassignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerassignment  
  template:
    metadata:
      labels:
        app: dockerassignment
    spec:
      containers:
      - name: dockerassignment
        image: dockerassignment-0.0.1:1.0
        ports:
        - containerPort: 8085   